### ISSUE TITLE
希望添加空行匹配正则

### ISSUE THREAD

**Issue by ati46** [zhoriya/idea-rule#1]
希望添加空行匹配正则

**Comment by Linindoo** [comment]
空行匹配正则是什么意思，是指一个正则规则匹配一个空行吗？

**Comment by ati46** [comment]
![image](https://user-images.githubusercontent.com/33859622/81139991-662a3880-8f9a-11ea-8fd5-a5007e83e229.png)
类似这样，文本中有一些空行， 可以通过正则把它去掉或这个替换为想要的内容

**Comment by Linindoo** [comment]
> ![image](https://user-images.githubusercontent.com/33859622/81139991-662a3880-8f9a-11ea-8fd5-a5007e83e229.png)
> 类似这样，文本中有一些空行， 可以通过正则把它去掉或这个替换为想要的内容

这个想法不错，不过我这里是插件仓库，数据直接使用的[any-rule](https://github.com/any86/any-rule)的数据，我这边可以做到，不过建议你最好去那边仓库提交issues或者直接贡献代码
