### ISSUE TITLE
IDEA2022版本似乎不能自定义正则

### ISSUE THREAD

**Issue by blueiky** [zhoriya/idea-rule#10]
![image](https://user-images.githubusercontent.com/51806785/190292373-3289749a-b29c-40bf-bc85-24691e9637e2.png)

IDEA版本：
![image](https://user-images.githubusercontent.com/51806785/190292436-d55e2478-d584-44af-8069-c98649f36ceb.png)

**Comment by Linindoo** [comment]
可以升级了
