### ISSUE TITLE
自定义规则再次打开文件会被覆盖

### ISSUE THREAD

**Issue by Gu-code99** [zhoriya/idea-rule#11]
IDE Version：IntelliJ IDEA 2021.1.3 (Community Edition)
Any-Rule Version：1.0.4
规则页面：
![image](https://user-images.githubusercontent.com/62836662/199906599-4b3f3992-380c-4135-b032-a4bbdff380db.png)
设置中显示的规则：
![image](https://user-images.githubusercontent.com/62836662/199906665-103c792f-545f-4002-8f6d-36c8dc1cd2c4.png)
添加自定义规则：
![image](https://user-images.githubusercontent.com/62836662/199906964-882d1e7c-e834-421f-a9dc-bb53709e50fb.png)
再次打开规则页面：
![image](https://user-images.githubusercontent.com/62836662/199907041-4032d8c4-cca3-4499-a8d0-e695e3d6e79b.png)
再次打开设置页面：
![image](https://user-images.githubusercontent.com/62836662/199907107-ebc79b3c-9f8b-49d1-8aaf-3a1b2bc739ba.png)

**Comment by Linindoo** [comment]
更新下插件版本吧
