### ISSUE TITLE
2023.1版本idea无法更新正则

### ISSUE THREAD

**Issue by XuJincai** [zhoriya/idea-rule#12]
更新前
![2023-04-06_135839](https://user-images.githubusercontent.com/16322049/230285279-c67c0081-76e6-4222-821e-b63b1887ee6e.png)
更新后
![2023-04-06_135855](https://user-images.githubusercontent.com/16322049/230285324-7ad4cdc6-ba88-4550-98a7-5725e52b3ef7.png)
保存后又变回原先
![2023-04-06_135914](https://user-images.githubusercontent.com/16322049/230285375-fcfa9170-454c-4be8-a7e5-d6a5b5bf78b7.png)
idea版本
![2023-04-06_140043](https://user-images.githubusercontent.com/16322049/230285423-9b0f1f58-49f9-4bbe-ba6a-7394d6ec6884.png)

**Comment by Linindoo** [comment]
已经可以升级了
