### ISSUE TITLE
webstorm2020.1.1中使用报错

### ISSUE THREAD

**Issue by qinzhiyonyan** [zhoriya/idea-rule#3]

**Comment by Linindoo** [comment]
嗯，找到原因了，应该是idea版本升级后有一些工具包移除了，我想办法兼容一下

**Comment by chest233** [comment]
> 嗯，找到原因了，应该是idea版本升级后有一些工具包移除了，我想办法兼容一下

大佬辛苦 期待你的新版本

**Comment by Linindoo** [comment]
> > 嗯，找到原因了，应该是idea版本升级后有一些工具包移除了，我想办法兼容一下
> 
> 大佬辛苦 期待你的新版本

https://github.com/zhoriya/idea-rule/releases
可以在最新的releases下载那个jar文件，通过本地导入的方式更新插件，上传官网审核还要花点时间
