### ISSUE TITLE
希望可以收录下RegexBuddy类库的

### ISSUE THREAD

**Issue by hoobiee** [zhoriya/idea-rule#5]
![image](https://user-images.githubusercontent.com/50859914/93740197-9b1eeb00-fc1c-11ea-9770-79ff130fc8d7.png)

**Comment by Linindoo** [comment]
可以考虑出一个自定义正则库

**Comment by Linindoo** [comment]
数据收录这个仓库不提供支持，不过可以完善本地自定义正则
