### ISSUE TITLE
在线更新库的URL地址貌似有问题，updateUrl需要重新更新有效地址

### ISSUE THREAD

**Issue by gudian1618** [zhoriya/idea-rule#6]

**Comment by gudian1618** [comment]
默认的有些正则表达式，比如邮箱等无法正确识别显示和使用，通过手动配置后生效。但是重启idea后失效。自动更新地址无效貌似，无法正确链接。

**Comment by Linindoo** [comment]
> 默认的有些正则表达式，比如邮箱等无法正确识别显示和使用，通过手动配置后生效。但是重启idea后失效。自动更新地址无效貌似，无法正确链接。

嗯，确实存在这种问题，应该是字符转义没有处理好

**Comment by MiaoWei814** [comment]
我滴天,这个链接能不能给一个有效的

**Comment by Linindoo** [comment]
> 我滴天,这个链接能不能给一个有效的

#9

**Comment by Linindoo** [comment]
已修复
