### ISSUE TITLE
右键图片特大 占满屏幕

### ISSUE THREAD

**Issue by admlke** [zhoriya/idea-rule#7]
![image](https://user-images.githubusercontent.com/24238594/123361010-de89f980-d5a0-11eb-9f01-166b0b743eba.png)

**Comment by Linindoo** [comment]
怎么这么大，吓死个人

**Comment by Linindoo** [comment]
麻烦提供一下系统和软件版本，我测试一下 @admlke

**Comment by Linindoo** [comment]
并不能复现
