### ISSUE TITLE
idea更新链接无效

### ISSUE THREAD

**Issue by MiaoWei814** [zhoriya/idea-rule#9]
idea更新的连接是无效的,并且连最基本的邮箱是没有的,希望能解决这一个问题

**Comment by Linindoo** [comment]
> idea更新的连接是无效的,并且连最基本的邮箱是没有的,希望能解决这一个问题

这个是github提供的地址，偶有失效，最好的方法是配置代理访问。
我看下能不能找个cdn加速一下

**Comment by MiaoWei814** [comment]
好的吧,找到就更新一下版本

**Comment by Linindoo** [comment]
> 好的吧,找到就更新一下版本

他原来的工程没有加cdn，我不太想重新维护一套工程，所以我fork了他的仓库加了一层cdn，你可以试试这个地址 [https://www.52zhoujia.cn/any-rule/packages/www/src/RULES.js](https://www.52zhoujia.cn/any-rule/packages/www/src/RULES.js)
这里之所以这样设计是为了灵活，如果未来他添加了cdn的话，用户手动修改地址即可

**Comment by MiaoWei814** [comment]
好吧 我已经修改了连接已经更新了,, 那这个地址是你这更新维护吗?

**Comment by Linindoo** [comment]
> 好吧 我已经修改了连接已经更新了,, 那这个地址是你这更新维护吗?

是的，是我自己的cdn，如果他那边更新版本，我这里可以进行合并，更新cdn就行

**Comment by MiaoWei814** [comment]
好的 谢谢了哦

**Comment by Linindoo** [comment]
> 好的 谢谢了哦

不客气
